### ISSUE TITLE
Android 6.0字符显示异常

### ISSUE THREAD

**Issue by liyk123** [aaa1115910/bv#1]
问题描述
------

Android 6.0字符显示异常

![image](https://liyk.live/bug/bug-cut_widechar.png)

复现方法
------

打开任意含有UTF-16加粗字符字符标题的视频，例如 https://www.bilibili.com/video/BV1Ce4y1g7Yk

测试平台
------

安卓官方模拟器
小米全面屏电视pro E32S
Samsung Galaxy S5

**Comment by aaa1115910** [comment]
e8e7bb3d43c38a1db99b1ac0ab1d1de437b6c832

感谢 @liyk123 大佬的帮助
