### ISSUE TITLE
建议增加推荐

### ISSUE THREAD

**Issue by yangchaobalck** [aaa1115910/bv#104]
### 问题描述

一直在使用大佬的，BBLL平板电视缝合怪用起怪怪的，希望大佬抽时间把推荐，一 天无聊就可以在电视上面刷推荐 
 了 ,希望大佬！！！能把这个功能 加 上 ！！辛苦了！！！

### 描述解决方案

增加推荐

**Comment by aaa1115910** [comment]
投稿时间不是有的吗，多个功能麻烦分开写多个issues

yangchaobalck ***@***.***> 于 2023年5月27日周六 20:41写道：

**Comment by aaa1115910** [comment]
重复了😮‍💨，推荐这个在做移动端的时候会顺便带上，在这之前还要先把 gRPC 接口 #103 给做了
Duplicate of #41
