### ISSUE TITLE
能关掉万恶的PCDN和MCDN吗?

### ISSUE THREAD

**Issue by b1456089826** [aaa1115910/bv#109]
### 问题描述

B 站 CDN 分类

根据自己打开不同热度不同类型的视频结合网上搜集的信息，大致分为以下几种：

    服务商 CDN
    upos-sz-mirror****.bilivideo.com
    看域名应该是服务商方案
    腾讯：cos,cosb,coso1,coso2,bos
    金山：ks3,ks3b,ks3c,ks32
    七牛：kodo,kodob
    华为：hw,hwb,uphw,js
    阿卡迈（海外）：akamai
    自建 CDN (?)
    cn-****-dx-v-**.bilivideo.com
    可能是 B 站的自建服务器其中可以看到省份和城市首字母缩写
    MCDN
    xxxxx(ip地址).mcdn.bilivideo.com
    xy99x999x99x99xy.mcdn.bilivideo.cn
    查了一圈只在京东云发现了 [MCDN](https://docs.jdcloud.com/cn/mcdn/product-overview)，可能是京东云无线宝相关？也可能是京东云+无线宝相互配合？
    怀疑 MCDN 包含无线宝的原因是 IP 段为家宽段
    PCDN
    ********.v1d.szbdyd.com
    到这就完全看脸了，各个地区上行带宽不可控，你连接到的节点与你的距离不可控，极端环境下甚至无法顺利播放 1080+

### 描述解决方案

目前发现app在播放视频时会连接MCDN，导致速度巨慢无比还可能会报错，问下大佬能关掉PCDN和MCDN，走服务商CDN吗？

**Comment by aaa1115910** [comment]
可以尝试在设置中切换使用 app 接口，使用 app 接口获得的播放地址直接就是 ip + 端口号
