### ISSUE TITLE
暂停播放时显示几秒进度条

### ISSUE THREAD

**Issue by loseheaven** [aaa1115910/bv#11]
### 问题描述

有这么几种情况：
1、想看下当前视频有多长
2、这个视频好喜欢，看看进度条还能撑多久
3、有事暂时不能在电视上看了，先看看播到哪了，晚些用别的设备继续看
………………
之类的，目前只有前进或后退时能看到播放进度条，暂停一下看下当前播放进度条是很好的一个方式，很多播放器&166和官方小电视也都是这样的，点下暂停的时候，短暂的显示几秒播放进度条，然后再消失；

### 描述解决方案

点下暂停的时候，短暂的显示几秒播放进度条，然后再消失

**Comment by aaa1115910** [comment]
和旧版官方版一样，按`下键`

**Comment by loseheaven** [comment]
> 

原来如此，一直没发现👍🏻
