### ISSUE TITLE
建议增加自动播放下一集功能

### ISSUE THREAD

**Issue by Hoku122** [aaa1115910/bv#12]
### 问题描述

目前多集视频播放完一集后，需要退出播放画面再选下一集，比较不方便，希望能有播放页选集和自动连播功能

### 描述解决方案

添加自动播放下一集
添加播放页面选集

**Comment by tsui603** [comment]
这个功能我也比较需要 哈哈

**Comment by liyk123** [comment]
做好这个大概就能把版本号变成1.0了吧😂
