### ISSUE TITLE
播放视频不是黑屏就是花屏

### ISSUE THREAD

**Issue by wongada001** [aaa1115910/bv#121]
### 问题描述

首页所有视频缩略图全部没有，都是黑乎乎的一片，然后播放视频所有 编码格式和分辨率都试了，不是黑屏就是花屏，没发正常播放

### 描述解决方案

首页所有视频缩略图全部没有，都是黑乎乎的一片，然后播放视频所有 编码格式和分辨率都试了，不是黑屏就是花屏，没发正常播放

### 描述备选方案

是否可以调用系统解码

**Comment by aaa1115910** [comment]
可

**Comment by wongada001** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月3日(星期天) 晚上10:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aaa1115910/bv] 播放视频不是黑屏就是花屏 (Issue #121)





 
你啥东西也不提供，我难道还能赛博看病，需要提供什么信息我在 Bug 报告模板  模板里写得很清楚

**Comment by wongada001** [comment]
BV-201-0.1.2.r201.6abdbcd.release 这个版本视频编码选择av1有视频画面，但选择360p的分辨率会卡顿，选择更高分辨率直接卡死


最新版的选择av1就黑屏，其他的h.264和265都是花屏

**Comment by aaa1115910** [comment]
**请更新应用，该项目不对旧版本提供长期维护**
解码都是使用的系统解码，你系统能解码什么就能放什么，如需播放av1请更换支持av1解码的设备

**Comment by aaa1115910** [comment]
> BV-201-0.1.2.r201.6abdbcd.release 这个版本视频编码选择av1有视频画面，但选择360p的分辨率会卡顿，选择更高分辨率直接卡死 最新版的选择av1就黑屏，其他的h.264和265都是花屏 Message ID: ***@***.***&gt;

我貌似之前看花眼了，av1 软解因为目前没有什么老旧设备能流畅带动，且会引发未知错误导致播放器无法播放，已于 2.0.0.r397 移除
