### ISSUE TITLE
合集分P播放完后跳转错误

### ISSUE THREAD

**Issue by FadeJay** [aaa1115910/bv#122]
### Bug 描述

当选集里有多个合集时，播放完除第一个合集的其他合集的视频时都会跳转到第一个合集的第1P

### 复现问题的步骤

```plain text
1.播放视频https://www.bilibili.com/video/BV1o84y1275v
2.播放完跳转到第一个合集的第一P https://www.bilibili.com/video/BV1sH4y1k7ie
```

### 预期行为

期望跳转到当前合集的下一P

### 应用版本

0.2.5.r590.968b217.release

### Android 版本

Androuid 9

### 设备厂商及型号

TCL

### 遇到问题的视频 avid 或 bvid

BV1o84y1275v

**Comment by aaa1115910** [comment]
不是选集里有多个合集，是合集里有多个分组（
