### ISSUE TITLE
Region Block 验证机制优化

### ISSUE THREAD

**Issue by chenyiping1995** [aaa1115910/bv#124]
### 问题描述

当前 Region Block 验证机制为 IPv6 优先，而大部分梯子不支持 IPv6 的透明代理。

### 描述解决方案

优先使用 IPv4 请求验证 URL，或者指定使用已知只使用 IPv4 的 Cloudflare URL 作为验证 URL，例如 `https://1.1.1.1/cdn-cgi/trace` 。

**Comment by aaa1115910** [comment]
![image](https://github.com/aaa1115910/bv/assets/34527143/55e04aae-02b8-4365-b52a-109f6fdeb1bd)
我这甚至都打不开 1.1.1.1 ......

**Comment by chenyiping1995** [comment]
> ![image](https://private-user-images.githubusercontent.com/34527143/300269979-55e04aae-02b8-4365-b52a-109f6fdeb1bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1Mzc0NzEsIm5iZiI6MTcwNjUzNzE3MSwicGF0aCI6Ii8zNDUyNzE0My8zMDAyNjk5NzktNTVlMDRhYWUtMDJiOC00MzY1LWI1MmEtMTA5ZjZmZGViMWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDE0MDYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmYzhiZTI2ZDY5ZTcxYTY4YzBhNjA0NGM5MzQwZjkxODU2OWNkZDEwMzExYTdlODM4NGZkYzlhY2NhMTZmMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n0u7lOeZm744CDhYF7SFZLnHiEhsPNsKWL2zrI_JFww) 我这甚至都打不开 1.1.1.1 ......

如果打不开的话就判定为 Location=CN 即可。
