### ISSUE TITLE
编译签名后无法在小米13上安装

### ISSUE THREAD

**Issue by yangyaojia** [aaa1115910/bv#126]
### Bug 描述

fork项目后，通过作者的github action Alpha Build Manually (Without sign) 进行编译。编译后通过keytool生成keystore文件，并通过jarsigner进行签名。但是签名后的apk无法在小米手机（澎湃OS）上安装，提示 

解析软件包时出现问题。（33）
详细信息：packageInfo is null

但是安装作者提供的apk是可以的

### 复现问题的步骤

```plain text
第一步，fork 作者的项目
第二步，生成google-services.json
第三步，通过action Alpha Build Manually (Without sign) 进行编译，下载 universal 版本
第四步，通过jarsigner将keytool生成keystore文件签名到编译后的apk
第五步，发送到小米手机安装，报错无法安装
```

### 预期行为

请问大佬该如何正确签名使得apk可以在小米13上安装呢？

### 该项目不确认已更新到以下所示的最新版本

- [X] 我已更新到最新版本

### 当前版本号

0.2.6.r603.91cff92

### Android 版本

Android 14

### 设备厂商及型号

Xiaomi 13

**Comment by aaa1115910** [comment]
这是 Android R 引入的新特性，请使用 v2 签名

[APK Signature Scheme v2 now required](https://developer.android.com/about/versions/11/behavior-changes-11#minimum-signature-scheme)

**Comment by yangyaojia** [comment]
好的，谢谢。打上v1+v2+v3的签名后可以正常安装了
