### ISSUE TITLE
Web接口无法播放视频

### ISSUE THREAD

**Issue by FadeJay** [aaa1115910/bv#127]
### Bug 描述

当设置里接口偏好设置为Web时无法播放视频，设置为App时正常

### 复现问题的步骤

```plain text
设置里接口偏好设置为Web
```

### 预期行为

能够正常播放视频

### 截图

![Screenshot_20240229-222723](https://github.com/aaa1115910/bv/assets/15902208/cde70884-5c74-41b5-a35b-a74f771cb53f)

### 该项目不确认已更新到以下所示的最新版本

- [X] 我已更新到最新版本

### 当前版本号

0.2.6.r606.ed981b8.release

### Android 版本

Androuid 9

### 设备厂商及型号

TCL

**Comment by tzz1040** [comment]
我也遇到此问题，暂时切换到APP接口解决

**Comment by asphodelus092** [comment]
遇到了同样的问题，似乎是B站改过端口了？暂时切换到APP接口解决，但是这样会没有杜比选项
