### ISSUE TITLE
建议增加观看直播功能

### ISSUE THREAD

**Issue by zxc135781** [aaa1115910/bv#13]
### 问题描述

希望能增加观看直播的功能

### 描述解决方案

No response

**Comment by aaa1115910** [comment]
不想做

**Comment by drw2005** [comment]
增加直播版块就是完全体了，请大佬考虑啊。

**Comment by qwr5650** [comment]
> 增加直播版块就是完全体了，请大佬考虑啊。

对呀，BL都有这个功能啊
