### ISSUE TITLE
建议增加用户锁功能

### ISSUE THREAD

**Issue by JackChenH** [aaa1115910/bv#133]
### 问题描述

在电视上使用的时候难免会遇到朋友来家里 家里人来家里的情况 有些状况下 不太想要家里人看到b站账号 也不想让别人随便增加浏览记录 烦请增加用户锁或者软件锁功能 谢谢

### 描述解决方案

可以增加类似于smarttubenext的一个登录账号一个锁的功能
或者可以直接弄一个软件锁
上锁或者解锁方式建议就用方向键上下左右就好了
感谢大佬！

**Comment by aaa1115910** [comment]
用户锁倒是可以考虑一下
目前不想随便增加浏览记录可以先打开隐身模式凑合用着，就在主界面右上角用户点进去就能看到
