### ISSUE TITLE
手动输入关键词搜索，显示结果为空，或者一两个

### ISSUE THREAD

**Issue by FrankWang2077** [aaa1115910/bv#139]
### Bug 描述

手动输入关键词搜索，显示结果为空，或者一两个

### 复现问题的步骤

```plain text
手动输入关键词搜索，显示结果为空，或者一两个
```

### 预期行为

搜索结果正常显示

### 请确认已更新到以下所示的最新版本

已更新到最新 Alpha 版

### 当前版本号

Alpha

### Android 版本

13

### 设备厂商及型号

Sony

### 遇到问题的视频 avid 或 bvid

Any

**Comment by aaa1115910** [comment]
![image](https://github.com/aaa1115910/bv/assets/34527143/4f19d357-6ac4-412b-bb6c-f47eb119d5ec)
