### ISSUE TITLE
播放4K视频时被下采样至1080p的电视内置系统UI分辨率，此时HDR无法被电视识别

### ISSUE THREAD

**Issue by zhm86** [aaa1115910/bv#145]
### Bug 描述

TCL 85q10k电视的Android 11系统和UI分辨率是1080p，在电视系统里安装BV，播放4K视频和HDR视频时，会被下采样到1080p输出，此时电视无法识别到HDR视频。弹幕已关闭。
在电视系统中安装其他播放器打开4K HDR的m3u8链接时，此电视能正常识别HDR并点对点播放4K HDR视频。
手头只有这一台4K电视，没在其他4K电视上测试过。
搜索了一下，此问题可能与ExoPlayer的渲染方式SurfaceView和PlayerView有关，当然也有可能是我电视系统的问题。
https://github.com/google/ExoPlayer/issues/6083#issuecomment-504904106

### 复现问题的步骤

```plain text
搜索4K或者Dolby Vision，打开任意4K视频，4K视频会被下采样至1080p播放，电视无法识别到HDR视频。
```

### 预期行为

电视识别到HDR视频，并且点对点播放4K视频。

### 请确认已更新到以下所示的最新版本

已更新到最新 Release 版

### 当前版本号

r629

### Android 版本

Android 11

### 设备厂商及型号

TCK - 85Q10K

**Comment by aaa1115910** [comment]
我自己电视上4k点对点视频播放起来没有问题🤔

**Comment by aaa1115910** [comment]
可能是因为我系统是 Android 12 for TV，从 Android 12 开始就支持原生的 4K 分辨率 UI，所以我这边没问题？我得找个低版本系统测试一下

**Comment by liyk123** [comment]
首先要确认你的设备是否支持这种格式的解码输出，BV的设置里有个条目，你可以确认一下，还有一个办法，就是把视频下载下来用本地播放器看看

**Comment by zhm86** [comment]
虽然1080p输出，但是播放视频时，日志显示获取到的视频是HDV或HVC或4K，而且能够流畅播放，说明硬解成功。
我用系统自带播放器测试了手头的样片：
4K AV1 60FPS WEBM正常
4K VP9 60FPS WEBM正常
4K HEVC 60FPS Dolby Vision Dolby Atmos MP4正常，Dolby Vision亮度、颜色正常

8K VP9 24FPS MKV无法播放
8K VP9 60FPS HDR WEBM无法播放
4K VVC 60FPS MP4无法播放

此电视的SoC是联发科MT9653，官网资料显示可以硬解VVC (H.266)和AVS3，有待进一步测试

**Comment by liyk123** [comment]
> 虽然1080p输出，但是播放视频时，日志显示获取到的视频是HDV或HVC或4K，而且能够流畅播放，说明硬解成功。 我用系统自带播放器测试了手头的样片： 4K AV1 60FPS WEBM正常 4K VP9 60FPS WEBM正常 4K HEVC 60FPS Dolby Vision Dolby Atmos MP4正常，Dolby Vision亮度、颜色正常
> 
> 8K VP9 24FPS MKV无法播放 8K VP9 60FPS HDR WEBM无法播放 4K VVC 60FPS MP4无法播放
> 
> 此电视的SoC是联发科MT9653，官网资料显示可以硬解VVC (H.266)和AVS3，有待进一步测试

我的意思是你要下载b站出问题的那个视频用系统播放器播放，b站的编码不一定是你的机器支持的

**Comment by zhm86** [comment]
用隔壁的BBLL软件在同一台电视测试结果如下，测试视频为www.bilibili.com/video/BV16o4y1Y7rQ

![83bdde7f04fd65ce39821f913f05427](https://github.com/user-attachments/assets/31aaceec-5cce-4c44-b2db-ef124bfd7652)
BBLL播放时电视能够识别并自动切换到Dolby Vision点对点4K输出，亮度颜色正常。

![8d2f538ff4b8db5c746443d6c8b94ff](https://github.com/user-attachments/assets/97507c02-bf12-46cb-874a-51041c92d8a8)
电视的解码器信息中包含Dolby Vision解码器

![67e3b1f3c427ca67ff75491cdbc3935](https://github.com/user-attachments/assets/44d14d6e-d56f-4a86-a9e7-1838d13de876)
用BV播放相同视频时，日志显示获取到4K Dolby Vision编码视频，但是以1080p的UI分辨率播放，电视无法识别到Dolby Vision内容。手机拍摄对焦有问题，但能够看出第2行的4K Dolby Vision

**Comment by aaa1115910** [comment]
我没有办法复现，也没有支持杜比的电视去测试🥹

**Comment by zhm86** [comment]
我觉得不需要找支持杜比的电视。
只需找一台4K屏幕的电视，电视的系统=<安卓11
或者与电视相连接的机顶盒的系统=<安卓11
此时系统UI分辨率是1080p，测试BV播放4K视频时，能否4K点对点输出即可。

**Comment by aaa1115910** [comment]
我电视 4K Android 5，因为系统证书有效期问题无法播放。。。

zhm86 ***@***.***> 于 2024年8月2日周五 00:01写道：

**Comment by zhm86** [comment]
给你添麻烦了。
我不懂安卓开发，不知道你说的证书是否跟HTTPS有关。
是否有可能，稍微改动代码做一个测试版本，播放时不去获取B站的某个视频内容，而是直接把某个本地4K视频喂给Exoplayer，不知道这样能否绕开证书，也不知道修改的工程量大不大。
如果这个bug确实存在，那么意味着安卓11和以下系统的用户，实际上看到的4K视频都是1080p下采样的结果。

**Comment by aaa1115910** [comment]
> 给你添麻烦了。 我不懂安卓开发，不知道你说的证书是否跟HTTPS有关。 是否有可能，稍微改动代码做一个测试版本，播放时不去获取B站的某个视频内容，而是直接把某个本地4K视频喂给Exoplayer，不知道这样能否绕开证书，也不知道修改的工程量大不大。 如果这个bug确实存在，那么意味着安卓11和以下系统的用户，实际上看到的4K视频都是1080p下采样的结果。

你说的对，把视频下下来，改改代码本地播放，我居然没想到

**Comment by aaa1115910** [comment]
> 给你添麻烦了。 我不懂安卓开发，不知道你说的证书是否跟HTTPS有关。 是否有可能，稍微改动代码做一个测试版本，播放时不去获取B站的某个视频内容，而是直接把某个本地4K视频喂给Exoplayer，不知道这样能否绕开证书，也不知道修改的工程量大不大。 如果这个bug确实存在，那么意味着安卓11和以下系统的用户，实际上看到的4K视频都是1080p下采样的结果。

我这边在 Android 5 的 4K 电视（1080pui）上播放点对点的测试视频 `BV1qK411N7Bu`（下载到本地播放）没有出现问题，和在 Android 12 下（4kui）的表现一样

**Comment by zhm86** [comment]
终于找到原因了，竟然是因为非会员无法获取到4K清晰度视频。
理论上，官方的限制就是，非会员无法观看1080p60帧以上的清晰度。
但是，在BV设置清晰度和编码后，虽然播放器日志提示获取到4K以及Dolby编码视频，然而非会员获取到的视频真实清晰度只有1080p。
目前只有手机端的6.40提取版能实现非会员获取4K清晰度视频。
开通会员后，BV能够获取真正的4K、Dolby Vision视频，电视也能识别到Dolby Vision内容。

同时还发现了一个bug，即使设置了获取Dolby Atmos音频，播放时最高只能获取到192k音频，同一个视频用BBLL能够正常获取到eac3编码的Dolby Atmos音频
www.bilibili.com/video/BV1vi421k7Zu

**Comment by aaa1115910** [comment]
> 终于找到原因了，竟然是因为非会员无法获取到4K清晰度视频。 理论上，官方的限制就是，非会员无法观看1080p60帧以上的清晰度。 但是，在BV设置清晰度和编码后，虽然播放器日志提示获取到4K以及Dolby编码视频，然而非会员获取到的视频真实清晰度只有1080p。 目前只有手机端的6.40提取版能实现非会员获取4K清晰度视频。 开通会员后，BV能够获取真正的4K、Dolby Vision视频，电视也能识别到Dolby Vision内容。
> 
> 同时还发现了一个bug，即使设置了获取Dolby Atmos音频，播放时最高只能获取到192k音频，同一个视频用BBLL能够正常获取到eac3编码的Dolby Atmos音频 [www.bilibili.com/video/BV1vi421k7Zu](http://www.bilibili.com/video/BV1vi421k7Zu)

日志提示4k确实是一个bug，此处判断选定清晰度和

> 终于找到原因了，竟然是因为非会员无法获取到4K清晰度视频。 理论上，官方的限制就是，非会员无法观看1080p60帧以上的清晰度。 但是，在BV设置清晰度和编码后，虽然播放器日志提示获取到4K以及Dolby编码视频，然而非会员获取到的视频真实清晰度只有1080p。 目前只有手机端的6.40提取版能实现非会员获取4K清晰度视频。 开通会员后，BV能够获取真正的4K、Dolby Vision视频，电视也能识别到Dolby Vision内容。
> 
> 同时还发现了一个bug，即使设置了获取Dolby Atmos音频，播放时最高只能获取到192k音频，同一个视频用BBLL能够正常获取到eac3编码的Dolby Atmos音频 [www.bilibili.com/video/BV1vi421k7Zu](http://www.bilibili.com/video/BV1vi421k7Zu)

设置里的接口偏好是 app 还是 web

**Comment by zhm86** [comment]
将接口偏好改为Web后，能够正常获取到Dolby Atmos音频。问题解决。
总结就是，非会员并不能正常获取到1080p 60fps及更高清晰度视频，然而控制台输出是获取到了1080p 60fps及更高清晰度视频。
可能是控制台输出有误。

**Comment by aaa1115910** [comment]
更新最新 alpha 版
https://github.com/aaa1115910/bv/compare/alpha-r665...alpha-r669
