### ISSUE TITLE
点开up主的界面显示不出来任何内容（已加载0条数据）

### ISSUE THREAD

**Issue by pqyawa** [aaa1115910/bv#146]
### Bug 描述

点开up详情界面无法看到任何视频内容

### 复现问题的步骤

```plain text
在关注页面亦或是任意一视频详情界面点击up主，进入其详情界面，会不加载其任何内容，显示已加载0条数据。
```

### 预期行为

可以在up详情界面看见ta的视频，这对我而言很有需要

### 请确认已更新到以下所示的最新版本

已更新到最新 Release 版

### 当前版本号

0.2.7.1.r629.ece3e1a.release

### Android 版本

Android 10

### 设备厂商及型号

HUAWEI-KANT-270D

### 附加信息

上下移动的时候好卡qwq

**Comment by aaa1115910** [comment]
b154506e2768901d825b13e89421307936521c50
