### ISSUE TITLE
0.0.11直接播放不能了,按播放后显示loading后跳出

### ISSUE THREAD

**Issue by nick200000** [aaa1115910/bv#15]
### Bug 描述

0.0.11直接播放不能了,按播放后显示loading后跳出

### 复现问题的步骤

```plain text
0.0.11直接播放不能了,按播放后显示loading后跳出
```

### 预期行为

...

### 应用版本

...

### Android 版本

...

**Comment by aaa1115910** [comment]
你需要提供出现问题的详细信息，而不是直接说不能播放

**Comment by nick200000** [comment]
感谢回覆,麻烦看下我录的视频,谢谢
https://www.123pan.com/s/7LjA-WVQD3

**Comment by aaa1115910** [comment]
> 感谢回覆,麻烦看下我录的视频,谢谢 https://www.123pan.com/s/7LjA-WVQD3

你视频里提到的两个视频均正常播放，无法复现

**Comment by nick200000** [comment]
我是所有视频都是loading跳出的现象,如果可以的话,你发个能搜集log的测试版,我抓log给你分析,谢谢

**Comment by liyk123** [comment]
@nick200000 可以的话直接抓ADB的log吧

**Comment by liyk123** [comment]
> 我是所有视频都是loading跳出的现象,如果可以的话,你发个能搜集log的测试版,我抓log给你分析,谢谢

可以的话直接抓ADB的log吧

**Comment by nick200000** [comment]
https://www.123pan.com/s/7LjA-6VQD3
抓了一份log,我发现只要播放模式是H.264 H.265就会退出,只有AV1能播

**Comment by aaa1115910** [comment]
> https://www.123pan.com/s/7LjA-6VQD3 抓了一份log,我发现只要播放模式是H.264 H.265就会退出,只有AV1能播

播放 H.264 H.265 是使用系统硬解，能否播放与系统和硬件有关。

在你的日志里我并没有看到 crash 缓冲区日志，根据 system 缓冲区的日志的有用信息来看：

`I/am_crash( 3567): [3567,0,dev.aaa1115910.bv,818462276,Native crash,Aborted,unknown,0]`

这可能不是我的问题，我觉得可能是运行系统的 native 代码出现了异常，因为我 app 没写 native 部分，播放 H.265/264 也不会使用到依赖引入的 native 库

**Comment by liyk123** [comment]
> https://www.123pan.com/s/7LjA-6VQD3 抓了一份log,我发现只要播放模式是H.264 H.265就会退出,只有AV1能播

你的电视有kodi吗？可以流畅播放4k的h265的视频吗？还是说只有内置播放器才能放呢？

**Comment by nick200000** [comment]
> > https://www.123pan.com/s/7LjA-6VQD3 抓了一份log,我发现只要播放模式是H.264 H.265就会退出,只有AV1能播
> 
> 播放 H.264 H.265 是使用系统硬解，能否播放与系统和硬件有关。
> 
> 在你的日志里我并没有看到 crash 缓冲区日志，根据 system 缓冲区的日志的有用信息来看：
> 
> `I/am_crash( 3567): [3567,0,dev.aaa1115910.bv,818462276,Native crash,Aborted,unknown,0]`
> 
> 这可能不是我的问题，我觉得可能是运行系统的 native 代码出现了异常，因为我 app 没写 native 部分，播放 H.265/264 也不会使用到依赖引入的 native 库

我一直到0.0.10.R113都是正常的,到0.0.11.R125以后才有问题

**Comment by nick200000** [comment]
> > https://www.123pan.com/s/7LjA-6VQD3 抓了一份log,我发现只要播放模式是H.264 H.265就会退出,只有AV1能播
> 
> 你的电视有kodi吗？可以流畅播放4k的h265的视频吗？还是说只有内置播放器才能放呢？

我没装Kodi呢,不过走ALIST播4K或是用mx player nplayer这些都是正常的

**Comment by aaa1115910** [comment]
> > > https://www.123pan.com/s/7LjA-6VQD3 抓了一份log,我发现只要播放模式是H.264 H.265就会退出,只有AV1能播
> > 
> > 
> > 播放 H.264 H.265 是使用系统硬解，能否播放与系统和硬件有关。
> > 在你的日志里我并没有看到 crash 缓冲区日志，根据 system 缓冲区的日志的有用信息来看：
> > `I/am_crash( 3567): [3567,0,dev.aaa1115910.bv,818462276,Native crash,Aborted,unknown,0]`
> > 这可能不是我的问题，我觉得可能是运行系统的 native 代码出现了异常，因为我 app 没写 native 部分，播放 H.265/264 也不会使用到依赖引入的 native 库
> 
> 我一直到0.0.10.R113都是正常的,到0.0.11.R125以后才有问题

试试这个
[BV-134-0.0.12.r134.d1b3d02.release.zip](https://github.com/aaa1115910/bv/files/10259611/BV-134-0.0.12.r134.d1b3d02.release.zip)

**Comment by nick200000** [comment]
> > > > https://www.123pan.com/s/7LjA-6VQD3 抓了一份log,我发现只要播放模式是H.264 H.265就会退出,只有AV1能播
> > > 
> > > 
> > > 播放 H.264 H.265 是使用系统硬解，能否播放与系统和硬件有关。
> > > 在你的日志里我并没有看到 crash 缓冲区日志，根据 system 缓冲区的日志的有用信息来看：
> > > `I/am_crash( 3567): [3567,0,dev.aaa1115910.bv,818462276,Native crash,Aborted,unknown,0]`
> > > 这可能不是我的问题，我觉得可能是运行系统的 native 代码出现了异常，因为我 app 没写 native 部分，播放 H.265/264 也不会使用到依赖引入的 native 库
> > 
> > 
> > 我一直到0.0.10.R113都是正常的,到0.0.11.R125以后才有问题
> 
> 试试这个 [BV-134-0.0.12.r134.d1b3d02.release.zip](https://github.com/aaa1115910/bv/files/10259611/BV-134-0.0.12.r134.d1b3d02.release.zip)

这一版不会闪退了,测试过H.264,H.265,AV1,杜比世界了,谢谢
