### ISSUE TITLE
无法播放

### ISSUE THREAD

**Issue by hairixinye** [aaa1115910/bv#150]
### Bug 描述

web和app源播放时会灰屏

### 复现问题的步骤

```plain text
进入视频 出现情况
```

### 预期行为

可以正常播放

### 请确认已更新到以下所示的最新版本

已更新到最新 Alpha 版

### 当前版本号

r679

### Android 版本

Android 9

### 设备厂商及型号

coocaa-43p31

**Comment by aaa1115910** [comment]
日志

**Comment by hairixinye** [comment]
这应该是我设备问题
