### ISSUE TITLE
最新以及最近的几个alpha版本版本播放视频灰屏，只有声音和弹幕

### ISSUE THREAD

**Issue by KnightHartX** [aaa1115910/bv#151]
### Bug 描述

最新以及最近的几个alpha版本版本播放视频灰屏，只有声音和弹幕，如图所示，旧的alpha版本正常，从某个版本开始出问题。电视是小米s85 miniled，用的电视内置系统
![photo_2024-09-30_19-34-01](https://github.com/user-attachments/assets/1291ed81-a5ed-46d7-9dda-2ce2b08f2ac3)

### 复现问题的步骤

```plain text
正常点进任意视频即可复现
```

### 预期行为

播放视频灰屏，只有声音和弹幕

### 截图

![photo_2024-09-30_19-34-01](https://github.com/user-attachments/assets/fdae1eb8-2ae5-4e6c-98b8-52a40d1fcfa9)

### 请确认已更新到以下所示的最新版本

已更新到最新 Alpha 版

### 当前版本号

0.2.9.r679.2326055.alpha

### Android 版本

Android 11

### 设备厂商及型号

小米s85 miniled

### 遇到问题的视频 avid 或 bvid

任意视频

### 相关日志

[logs_manual_2024-09-28_18_02_22.log.txt](https://github.com/user-attachments/files/17189072/logs_manual_2024-09-28_18_02_22.log.txt)

**Comment by zhuxuetong** [comment]
![{2B4EC691-2716-4200-BF68-E10E26BEB377}](https://github.com/user-attachments/assets/3eba7b0d-8dc3-4205-907b-5fb50dfe0df6)
安卓9 模拟器也是这个问题

**Comment by aaa1115910** [comment]
最近几个版本的代码里我也就更新了播放器依赖 media3 的版本（1.3.1-> 1.4.1），其他代码都没动过，现在我打包了两个使用 1.3 和 1.5 的包你再试试？
- [media 1.3.1](https://github.com/aaa1115910/bv/actions/runs/11202395496/artifacts/2020798420)
- [media 1.5.0-alpha01](https://github.com/aaa1115910/bv/actions/runs/11202839370/artifacts/2020895614)

**Comment by KnightHartX** [comment]
> 最近几个版本的代码里我也就更新了播放器依赖 media3 的版本（1.3.1-> 1.4.1），其他代码都没动过，现在我打包了两个使用 1.3 和 1.5 的包你再试试？
> 
> * [media 1.3.1](https://github.com/aaa1115910/bv/actions/runs/11202395496/artifacts/2020798420)
> * [media 1.5.0-alpha01](https://github.com/aaa1115910/bv/actions/runs/11202839370/artifacts/2020895614)

经测试，这两个包更新后均无效果，复现问题仍然是灰屏、有声音、有弹幕
我又把近期的几个版本一个个试了下，发现669版本就一切正常，更新至673及以后版本后，均出现问题
合理猜想是669到673版本更新中某个组件出现bug，且之后版本一直未修复

**Comment by aaa1115910** [comment]
> > 最近几个版本的代码里我也就更新了播放器依赖 media3 的版本（1.3.1-> 1.4.1），其他代码都没动过，现在我打包了两个使用 1.3 和 1.5 的包你再试试？
> > 
> > * [media 1.3.1](https://github.com/aaa1115910/bv/actions/runs/11202395496/artifacts/2020798420)
> > * [media 1.5.0-alpha01](https://github.com/aaa1115910/bv/actions/runs/11202839370/artifacts/2020895614)
> 
> 经测试，这两个包更新后均无效果，复现问题仍然是灰屏、有声音、有弹幕 我又把近期的几个版本一个个试了下，发现669版本就一切正常，更新至673及以后版本后，均出现问题 合理猜想是669到673版本更新中某个组件出现bug，且之后版本一直未修复

669到673之间和播放相关的更新只有把播放器依赖 media3 从 1.3.1 更新到 1.4.1，现在降回 1.3.1也不行，太奇怪了🤔

**Comment by aaa1115910** [comment]
我可能找到 bug 了，使用 compose-tv 1.0.0（1.0.0-rc02+） 版本时这个作为最底层的 Surface 会莫名其妙跑到 VideoPlayer 的上面去挡住了视频，在高版本 Android 中看起来一切正常，但使用低版本 Android 就会出现问题

**Comment by aaa1115910** [comment]
https://issuetracker.google.com/issues/361611808

**Comment by KnightHartX** [comment]
> https://issuetracker.google.com/issues/361611808

最新版本已成功修复，完美解决😘😘💕
