### ISSUE TITLE
不能看大会员能看的格式了，之前可以

### ISSUE THREAD

**Issue by Iseink** [aaa1115910/bv#154]
### Bug 描述

没有错误，只是没有大会员格式可供选择了

### 复现问题的步骤

```plain text
打开任一需要大会员的视频观看
```

### 预期行为

能看大会员格式

### 截图
![Screenshot_20241024-151432](https://github.com/user-attachments/assets/9a4e9017-50a4-433b-b95b-b05b166b6a25)

### 请确认已更新到以下所示的最新版本

已更新到最新 Alpha 版

### 当前版本号

r685

### Android 版本

android 9

### 设备厂商及型号

CM311-1A-YST

### 遇到问题的视频 avid 或 bvid

112806963774057

### 相关日志
[logs_manual_2024-10-24_14:51:01.log](https://github.com/user-attachments/files/17502811/logs_manual_2024-10-24_14.51.01.log)

**Comment by aaa1115910** [comment]
请补充错误信息和日志

**Comment by Iseink** [comment]
已补充

**Comment by aaa1115910** [comment]
我这边一切正常，你开会员没

**Comment by Iseink** [comment]
从没开会员，难道bv不支持解锁画质！？我前几天还能看会员格式啊

**Comment by aaa1115910** [comment]
> 从没开会员，难道bv不支持解锁画质！？我前几天还能看会员格式啊

从来就不支持，你可能是遇到会员清晰度限免了
