### ISSUE TITLE
建议增加高宽比以及缩放模式设置

### ISSUE THREAD

**Issue by liyk123** [aaa1115910/bv#16]
### 问题描述

一些古老的视频存在高宽比错误的问题，可通过调整高宽比以及缩放模式得到纠正。

### 描述解决方案

缩放模式和高宽比都可以在AspectRatioFrameLayout中调整：
* com.google.android.exoplayer2.ui.AspectRatioFrameLayout#setResizeMode
* com.google.android.exoplayer2.ui.AspectRatioFrameLayout#setAspectRatio

### 描述备选方案

自定义布局

### 附加信息

可能包名不同

**Comment by aaa1115910** [comment]
调整画面比例的时候就需要更改缩放模式设置，因此我觉得没有必要把缩放模式单独做出来，会与画面比例调节冲突

**Comment by liyk123** [comment]
确实缩放模式对于电视是没必要的，基本上不存在那种1:1显示的需求
