### ISSUE TITLE
播放杜比视界视频的时候画面全部变绿

### ISSUE THREAD

**Issue by 264088719** [aaa1115910/bv#18]
### Bug 描述

播放设备：hk1box机顶盒(SoC:晶晨s905x3)
安卓版本：9.0
所有杜比视界视频播放时画面都会只显示绿色，如下图。

### 复现问题的步骤

```plain text
所有杜比视界画质的视频播放时出现。
```

### 预期行为

电视可以正常点亮HDR模式，这很棒，但是画面不正常，求解决。

### 截图

![9FE5DDFF-C6E2-4A21-9DF2-B5B4D771AD5E](https://user-images.githubusercontent.com/17814093/208289551-a1cf055e-3086-42ec-a15c-e5d0d4f36d89.jpeg)

### 应用版本

0.0.12.r133.fa7552.release

### Android 版本

安卓9.0

### 设备厂商及型号

东芝 u6900c 65寸

**Comment by aaa1115910** [comment]
你的盒子不支持杜比视界

**Comment by aaa1115910** [comment]
网上找了几个评测都没看到过该机型支持杜比。解码杜比也都是使用的硬解，硬解得到的画面只与机器本身有关。
