### ISSUE TITLE
希望增加视频字幕功能

### ISSUE THREAD

**Issue by Hoku122** [aaa1115910/bv#25]
### 问题描述

现在没有字幕功能，在观看某些使用cc字幕的视频时，会有些不便，希望可以添加显示cc字幕，谢谢

### 描述解决方案

1、增加视频cc字幕
2、如果可调节字幕大小及简繁转换就更好了

**Comment by aaa1115910** [comment]
b4527790da89da2b794b4c992c44145d0a49d18e
