### ISSUE TITLE
视频只有480和360P

### ISSUE THREAD

**Issue by purelovelx** [aaa1115910/bv#26]
### Bug 描述

如题，是我电视问题还是软件目前最高只支持480？望大大解忧

### 复现问题的步骤

```plain text
安装进去看视频就是480了
```

### 预期行为

可以看4k或者1080高帧率？

### 应用版本

0.0.012

### Android 版本

9

### 设备厂商及型号

tcl

**Comment by aaa1115910** [comment]
登录

**Comment by purelovelx** [comment]
Thanks♪(･ω･)ﾉ




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月22日(星期四) 中午12:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aaa1115910/bv] 视频只有480和360P (Issue #26)





 
登录
