### ISSUE TITLE
r152版本播放完毕不会自动退出

### ISSUE THREAD

**Issue by kjmnxcfdg** [aaa1115910/bv#27]
### Bug 描述

播放完毕不会自动退出，每个视频放完了都要手动点两次返回退出

### 复现问题的步骤

```plain text
每个视频都是这样
```

### 预期行为

希望下个版本修复

### 应用版本

0.0.14.r152.70b8fbe.release

### Android 版本

安卓9的电视盒子

**Comment by aaa1115910** [comment]
应用特性

**Comment by kjmnxcfdg** [comment]
> 应用特性

大佬，是播放的视频的界面，放完了不会自动退出。正常不应该是播放完视频后，自动退出到视频简介页面吗？

**Comment by aaa1115910** [comment]
> > 应用特性
> 
> 大佬，是播放的视频的界面，放完了不会自动退出。正常不应该是播放完视频后，自动退出到视频简介页面吗？

我不喜欢自动退出
