### ISSUE TITLE
15版本看台港澳番剧cc打开后不显示

### ISSUE THREAD

**Issue by kingstar101** [aaa1115910/bv#29]
### Bug 描述

更新版本后，打开台港澳番剧出现了CC字幕选择，但是选择字幕后，仍不显示

### 复现问题的步骤

```plain text
进入台港澳番剧
点击CC字幕
选择中文（繁体）
```

### 预期行为

出现字幕

### 应用版本

v0.0.15

### Android 版本

android 10

### 设备厂商及型号

X90J

**Comment by aaa1115910** [comment]
#28
