### ISSUE TITLE
CC字幕不记录打开状态

### ISSUE THREAD

**Issue by Labrador-QAQ** [aaa1115910/bv#31]
### Bug 描述

打开播放视频界面的cc字幕开关
播放新的视频又关闭了

### 复现问题的步骤

```plain text
播放视频
打开cc字幕
重新打开视频
CC字幕消失
```

### 预期行为

正常显示CC显示字幕

### 应用版本

0.0.16

### Android 版本

9/6

**Comment by aaa1115910** [comment]
暂时不打算做，因为部分视频有ai生成的字幕，但视频可能又自带硬字幕，这样可能会导致双重字幕，况且我也不知道你想要默认查看哪个字幕，到头来还不算要打开菜单设置
