### ISSUE TITLE
字体调大一些

### ISSUE THREAD

**Issue by huajiworld** [aaa1115910/bv#33]
### 问题描述

把字体放大一些，要不然电视屏幕太大，字太小看不清
现在这个字体大小感觉更适合在手机上用

### 描述解决方案

把字体放大，或者把界面控件放大

**Comment by aaa1115910** [comment]
我觉得默认大小正好。我还拿尺子比较了和 Google Play Store 的字体大小差别，发现大小都一样。

**Comment by huajiworld** [comment]
> 我觉得默认大小正好。我还拿尺子比较了和 Google Play Store 的字体大小差别，发现大小都一样。

但是在电视上看，真的感觉好小啊😂，还是希望能大一些，像官方版那样差不多

**Comment by aaa1115910** [comment]
> > 我觉得默认大小正好。我还拿尺子比较了和 Google Play Store 的字体大小差别，发现大小都一样。
> 
> 但是在电视上看，真的感觉好小啊😂，还是希望能大一些，像官方版那样差不多

没用过大电视，我也不可能瞎调，而且一加大那么正常显示的人又会觉得过大

**Comment by huajiworld** [comment]
> > > 我觉得默认大小正好。我还拿尺子比较了和 Google Play Store 的字体大小差别，发现大小都一样。
> > 
> > 但是在电视上看，真的感觉好小啊😂，还是希望能大一些，像官方版那样差不多
> 
> 没用过大电视，我也不可能瞎调，而且一加大那么正常显示的人又会觉得过大

那就加个选项可以吗？
