### ISSUE TITLE
需要TV端Leanback图标

### ISSUE THREAD

**Issue by qinlili23333** [aaa1115910/bv#35]
### 问题描述

![1673220281871719446040665299526](https://user-images.githubusercontent.com/24567775/211224213-bc79d8da-5a9e-4ee1-b557-97e19a6d924a.jpg)
没有Leanback图标，电视上桌面图标显示不美观

### 描述解决方案

添加独立的横向Leanback图标，大多数电视都使用Leanback图标作为默认桌面图标

**Comment by aaa1115910** [comment]
一直都有啊，无论是 Android 低版本还是高版本都能显示

https://github.com/aaa1115910/bv/blob/8f739de30d43808fc6141d2b257f0edb71d96992/app/src/main/AndroidManifest.xml#L76

![image](https://user-images.githubusercontent.com/34527143/211237272-bb5b1d0d-707a-48f7-b962-8a12845435a7.png)
![image](https://user-images.githubusercontent.com/34527143/211237700-b8b2c183-7bb8-495c-a99c-9c71f45d7efb.png)

**Comment by qinlili23333** [comment]
看来这是亚马逊给侧载加的限制，似乎唯一办法是注册亚马逊appstore上架
