### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by yushiyan** [aaa1115910/bv#36]
### 问题描述

在我的长虹电视（安卓5，hisi551）上软件界面有着严重的卡顿问题（非播放视频）包括弹幕都有种卡卡的感觉 我觉得可以先尝试优化一下性能后再添加一些新功能 会大幅度增加使用体验

### 描述解决方案

很期待作者能做这个软件 可以的话希望开放打赏码 我想献一份小力 加油！

### 附加信息

芜湖

**Comment by aaa1115910** [comment]
compose 在 ui 上很吃性能的，解决不了，这是软件特色！

yushiyan ***@***.***> 于 2023年1月10日周二 00:59写道：

**Comment by yushiyan** [comment]
彳亍口巴 弹幕卡貌似是我的幻觉 在放视频的时候左上角fps一直都是59或者60 但只要一返回软件就会立马掉帧 感谢回复

**Comment by aaa1115910** [comment]
如果在播放时打开菜单，那弹幕确实会疯狂掉帧

yushiyan ***@***.***> 于 2023年1月10日周二 01:16写道：
