### ISSUE TITLE
话音不同步，希望增加系统解码。

### ISSUE THREAD

**Issue by PPXNO1** [aaa1115910/bv#39]
### 问题描述

首先感谢作者的分享。
测试机器：华为智慧屏se55
系统版本：harmonyOS2.0.0
软件版本：Version 0.1.2.r201.6abdbcd.release
大部分视频会出现话音不同步的问题和掉帧的问题，切换了三种解码方式和更改分辨率，问题不能解决。问题可能是解码方式的原因引起的（我同时还安装了小爱音箱提取的魔改版B站，更改为系统解码可解决上述问题）

### 描述解决方案

希望增加系统解码
![image](https://user-images.githubusercontent.com/121994715/211721369-83466ae4-7efd-4d55-bfcc-16a4d22ec37b.png)

**Comment by liyk123** [comment]
ExoPlayer就是采用了系统解码啊。。。

**Comment by aaa1115910** [comment]
本来就是调用的系统解码

**Comment by PPXNO1** [comment]
我不懂，是个外行人，就是在贴吧看到下载的，算是一个体验用户吧。反正就是卡和话音不同步，但是我装的小爱音箱魔改版切换系统解码后很流畅，就是没有推荐和动态，得搜索着看，很不方便。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月11日(星期三) 中午1:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aaa1115910/bv] 话音不同步，希望增加系统解码。 (Issue #39)





 
ExoPlayer就是采用了系统解码啊。。。

**Comment by PPXNO1** [comment]
我不懂，是个外行人，就是在贴吧看到下载的，算是一个体验用户吧。反正就是卡和话音不同步，但是我装的小爱音箱魔改版切换系统解码后很流畅，就是没有推荐和动态，得搜索着看，很不方便。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月11日(星期三) 下午4:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aaa1115910/bv] 话音不同步，希望增加系统解码。 (Issue #39)





 
本来就是调用的系统解码

**Comment by aaa1115910** [comment]
> 我不懂，是个外行人，就是在贴吧看到下载的，算是一个体验用户吧。反正就是卡和话音不同步，但是我装的小爱音箱魔改版切换系统解码后很流畅，就是没有推荐和动态，得搜索着看，很不方便。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年1月11日(星期三) 中午1:09 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [aaa1115910/bv] 话音不同步，希望增加系统解码。 (Issue #39) ExoPlayer就是采用了系统解码啊。。。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

卡顿我无能为力，都是直接系统解码的，建议去使用隔壁 bbll

**Comment by niupiyang** [comment]
> > 我不懂，是个外行人，就是在贴吧看到下载的，算是一个体验用户吧。反正就是卡和话音不同步，但是我装的小爱音箱魔改版切换系统解码后很流畅，就是没有推荐和动态，得搜索着看，很不方便。 [。](#) ------------------ 原始邮件 ------------------ 发件人： _**@**_._**>; 发送时间： 2023年1月11日（星期三） 中午1：09 收件人： _**@**_.**_>;抄送： _**@**_._**>;_**@**_.**_>;主题： Re： [aaa1115910/bv] 话音不同步，希望增加系统解码。（问题 #39）ExoPlayer就是采用了系统解码啊。。。— 直接回复此电子邮件，在 GitHub 上查看或取消订阅。您收到此消息是因为您创作了线程。消息 ID：_**@**_.***>
> 
> 卡顿我无能为力，都是直接系统解码的，建议去使用隔壁 bbll

请问为何BBLL不会出现此类问题呢？

**Comment by aaa1115910** [comment]
> > > 我不懂，是个外行人，就是在贴吧看到下载的，算是一个体验用户吧。反正就是卡和话音不同步，但是我装的小爱音箱魔改版切换系统解码后很流畅，就是没有推荐和动态，得搜索着看，很不方便。 [。](#) ------------------ 原始邮件 ------------------ 发件人： _**@**_._**>; 发送时间： 2023年1月11日（星期三） 中午1：09 收件人： _**@**_.**_>;抄送： _**@**_._**>;_**@**_.**_>;主题： Re： [aaa1115910/bv] 话音不同步，希望增加系统解码。（问题 #39）ExoPlayer就是采用了系统解码啊。。。— 直接回复此电子邮件，在 GitHub 上查看或取消订阅。您收到此消息是因为您创作了线程。消息 ID：_**@**_.***>
> > 
> > 
> > 卡顿我无能为力，都是直接系统解码的，建议去使用隔壁 bbll
> 
> 请问为何BBLL不会出现此类问题呢？

请问我怎么能够知道BBLL为什么不会出现此类问题呢？
