### ISSUE TITLE
建议关于里面留下发布页地址

### ISSUE THREAD

**Issue by kjmnxcfdg** [aaa1115910/bv#4]
没发现昨晚更新了，昨晚只试用了r81版本。建议关于里面留下发布页地址，否则不知道在哪更新，我也是找了好久才找到这里。

试用是很流畅的，就是不记录历史记录和播放进度。这是硬伤，让我不得不换回贴吧第三方版本。

电视看起来会忘记时间过去了多久，大部分电视软件都会自带按键时显示当前时间，建议增加这个功能。

其他贴心功能，像点进视频自动播放，不用再多点一次确定之类，有就更好了。

还有加载视频时左下角很多加载提示，能否去掉呢？好久不用网页端，在电视上看见这类提示感觉怪怪的。

**Comment by aaa1115910** [comment]
关于里面那不就是发布页
播放进度历史极力会做的
显示时间、自动播放暂时不打算做
左下角我还得多考虑几下

问题建议请分开提便于跟踪
一个问题/建议一条 issue，不然不方便处理，所以这个 issue 我就先关闭了
