### ISSUE TITLE
希望能新增多 P 视频连续播放和视频内选择其他 P 功能

### ISSUE THREAD

**Issue by J03H82** [aaa1115910/bv#40]
### 问题描述

希望能新增多 P 视频连续播放和视频内选择其他 P 功能

### 描述解决方案
![08A79DB8-F063-4170-99EA-C56E17683B9D](https://user-images.githubusercontent.com/122437289/211759545-6b8aa3ad-54c2-453c-991d-32064bde4229.jpeg)

**Comment by aaa1115910** [comment]
d2dcd6e2d5142bf6f5006d4f8d917ec8364602f2

**Comment by aaa1115910** [comment]
Duplicate of #12
