### ISSUE TITLE
增加【推荐】分区

### ISSUE THREAD

**Issue by loseheaven** [aaa1115910/bv#41]
### 问题描述

目前版本中bv写作“热门推荐”的分区，实际为手机和166版本的“热门”，即全站所有人打开都一样的榜单
“推荐”分区在手机端的表现是针对登录用户平时的观影倾向性的推荐视频，应该也就是166版本首页上推荐的那些视频

### 描述解决方案

“热门推荐”改做“热门”，新增“推荐”分区，功能就清晰了也彻底完善了

**Comment by aaa1115910** [comment]
暂时并没有找到web端的个人推荐api

**Comment by loseheaven** [comment]
> 暂时并没有找到web端的个人推荐api

https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/video/recommend.md

大佬看一下这个是不是。不确定这是不是所谓的web端api，我简单看了下这个人收集的其他api，比如热门的api，和你代码里好像用的是同一个，这个推荐的api，url前面一部分看上去应该同一类接口

**Comment by aaa1115910** [comment]
> > 暂时并没有找到web端的个人推荐api
> 
> https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/video/recommend.md
> 
> 大佬看一下这个是不是。不确定这是不是所谓的web端api，我简单看了下这个人收集的其他api，比如热门的api，和你代码里好像用的是同一个，这个推荐的api，url前面一部分看上去应该同一类接口

这个是视频详细信息页里获取相关视频的 api

**Comment by loseheaven** [comment]
> > > 暂时并没有找到web端的个人推荐api
> > 
> > 
> > https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/video/recommend.md
> > 大佬看一下这个是不是。不确定这是不是所谓的web端api，我简单看了下这个人收集的其他api，比如热门的api，和你代码里好像用的是同一个，这个推荐的api，url前面一部分看上去应该同一类接口
> 
> 这个是视频详细信息页里获取相关视频的 api

原来如此，是我唐突了。
然后发现我最上面的描述也有错误的地方，166版本应该是没有用到“热门”接口，用的“排行”接口（全站&分区），避免错误信息误导大佬，特此纠正一下。

**Comment by peacefulprogram** [comment]
[web首页个性化推荐接口](https://github.com/peacefulprogram/BilibiliTv/blob/main/app/src/main/java/com/jing/bilibilitv/http/api/BilibiliApi.kt#L43)
看一下这个接口,缺点就是每次刷新重复的太多了

**Comment by tttwwy** [comment]
恩恩，可以考虑一下BBLL的推荐接口
