### ISSUE TITLE
希望增加评论和视频简介功能

### ISSUE THREAD

**Issue by 2496414612** [aaa1115910/bv#42]
### 问题描述

看视频没有评论少了很多乐趣，简介也包含着视频的很多信息，所以希望可以添加这两个板块，谢谢了，这个软件目前已经做的很棒了，如果加了这两个功能就是锦上添花，但是要是太麻烦了的话还是算了，不想为难开发者

### 描述解决方案

在视频的播放页的下面加上简介和弹幕图标，就像开关弹幕的那个开关的图标一样

**Comment by aaa1115910** [comment]
就是说，有没有一种可能，在0.0.1第一个版本0.0.1里就有了视频简介
评论不会做

**Comment by 2496414612** [comment]
> 就是说，有没有一种可能，在第一个版本0.0.1里就有了视频简介
> 评论不会做

啊这，我用这软件好几天了都没看到视频简介在哪里🥲，我再去看看吧

**Comment by aaa1115910** [comment]
> > 就是说，有没有一种可能，在第一个版本0.0.1里就有了视频简介
> > 评论不会做
> 
> 啊这，我用这软件好几天了都没看到视频简介在哪里smiling_face_with_tear，我再去看看吧

![Cache_5a1d72ad989877ca](https://user-images.githubusercontent.com/34527143/211969463-189fafa8-2e8f-4a36-ae99-bf9f3f17581f.png)

**Comment by 2496414612** [comment]
> > > 就是说，有没有一种可能，在第一个版本0.0.1里就有了视频简介
> > > 评论不会做
> > 
> > 啊这，我用这软件好几天了都没看到视频简介在哪里smiling_face_with_tear，我再去看看吧
> 
> ![Cache_5a1d72ad989877ca](https://user-images.githubusercontent.com/34527143/211969463-189fafa8-2e8f-4a36-ae99-bf9f3f17581f.png)
> 

作者我错了，我把你的软件和 blbl 搞混了，因为你们都是在 app center 发布，我一直以为是同一款软件，只不过名字不同而已🥲，我就说怎么找不到简介

**Comment by aaa1115910** [comment]
> > > > 就是说，有没有一种可能，在第一个版本0.0.1里就有了视频简介
> > > > 评论不会做
> > > 
> > > 
> > > 啊这，我用这软件好几天了都没看到视频简介在哪里smiling_face_with_tear，我再去看看吧
> > 
> > 
> > ![Cache_5a1d72ad989877ca](https://user-images.githubusercontent.com/34527143/211969463-189fafa8-2e8f-4a36-ae99-bf9f3f17581f.png)
> 
> 作者我错了，我把你的软件和 blbl 搞混了，因为你们都是在 app center 发布，我一直以为是同一款软件，只不过名字不同而已smiling_face_with_tear，我就说怎么找不到简介

坏
