### ISSUE TITLE
快进快退时不显示上方的标题栏

### ISSUE THREAD

**Issue by wjz2001** [aaa1115910/bv#43]
### 问题描述

快进快退时上方的标题栏和下方的进度条会同时显示，遮挡了一些视频画面和弹幕。

### 描述解决方案

快进快退时隐藏上方的标题栏，仅在按下键时显示标题栏。

**Comment by aaa1115910** [comment]
但是快进/退的时候画面是暂停的，遮挡与否影响不大

**Comment by wjz2001** [comment]
> 但是快进/退的时候画面是暂停的，遮挡与否影响不大

快进快退结束后会立刻开始播放，但此时画面仍然被遮挡，只能等待或按下键。

**Comment by aaa1115910** [comment]
> > 但是快进/退的时候画面是暂停的，遮挡与否影响不大
> 
> 快进快退结束后会立刻开始播放，但此时画面仍然被遮挡，只能等待或按下键。

你网速真快。。。。

**Comment by wjz2001** [comment]
> > > 但是快进/退的时候画面是暂停的，遮挡与否影响不大
> > 
> > 
> > 快进快退结束后会立刻开始播放，但此时画面仍然被遮挡，只能等待或按下键。
> 
> 你网速真快。。。。

另外进度条底下的空白可不可以去掉？这样进度条紧贴画面底部，又可以多漏一些画面

**Comment by aaa1115910** [comment]
1c21042fcd682912f0370d50ea630e689f609fdf
