### ISSUE TITLE
分P自动播放 

### ISSUE THREAD

**Issue by dragon0629** [aaa1115910/bv#45]
### 问题描述

有些视频分了好多P，每次结束都要退出重新进

### 描述解决方案

分P能不能自动播放下一个
OJZ
有些视频分了好多P，每次结束都要退出重新进，他可以自动播放下一P嘛？
另外作者NB！

**Comment by aaa1115910** [comment]
ebf3254032afd2181c92727804b1d0b9bb1fa50d

**Comment by aaa1115910** [comment]
Duplicate of #12
