### ISSUE TITLE
是否有可能支持遥控器的播放和快进快退按钮？

### ISSUE THREAD

**Issue by qinlili23333** [aaa1115910/bv#47]
### 问题描述

![image](https://user-images.githubusercontent.com/24567775/212502834-920e82c5-464a-46ba-9ab0-db3f16c5c010.png)

这是我目前所使用的火棒的遥控器，有一排播放和快退快进按钮。在Apple TV和115等app中可以正常工作，但目前在BV中这排按钮完全无效。

### 描述解决方案

在播放界面中，播放按钮应该和确定键的效果一样可以切换播放暂停，快退快进则与方向键有所区别，方向键为单次秒数进退，快退快进键则应该为一定倍速的持续前进后退直到按下播放键恢复。
在列表或详情界面，播放按钮应该按下后直接进入播放器。

### 描述备选方案

或许可以把长按快退快进键定义为快捷切换分p

### 附加信息

理论上这将同时修复Alexa语音控制不能暂停视频的问题

_No response_

**Comment by aaa1115910** [comment]
但我没这种遥控板来测试，这是个问题

**Comment by qinlili23333** [comment]
https://developer.amazon.com/docs/fire-tv/remote-input.html
这里有亚马逊给出的keycode参考，或许可以先对照着实现一下，我可以帮助测试

**Comment by aaa1115910** [comment]
添加了多个按键的事件监听 c7c2e2dbb16406cc957f3c497d88ba09429d7c7b
但我没有测试（懒+没遥控板
你可以在 https://github.com/aaa1115910/bv/actions/workflows/alpha.yml 获取最新版本试试

**Comment by qinlili23333** [comment]
测试了一下，快进快退正常，播放暂停有时候会抽搐，但至少肯定按键事件触发了，多半是同时监听播放暂停和播放/暂停独立事件冲突了
另外这个版本动态无法获取

**Comment by aaa1115910** [comment]
> 测试了一下，快进快退正常，播放暂停有时候会抽搐，但至少肯定按键事件触发了，多半是同时监听播放暂停和播放/暂停独立事件冲突了 另外这个版本动态无法获取

动态相关的代码很久没动过了，我自己使用倒是正常获取
播放暂停键鬼畜，看了一下代码发现是有东西写漏了
