### ISSUE TITLE
多p视频页面增加“显示全部分p”按钮

### ISSUE THREAD

**Issue by wjz2001** [aaa1115910/bv#49]
### 问题描述

现在多p视频页面没有这个按钮，有些攻略视频有几十上百p，往后翻很不方便。

### 描述解决方案

模仿番剧影视页面，它们都有一个放在最开头的“显示全部剧集”按钮，把它移植到视频页面并改为“显示全部分p”功能即可。

### 附加信息

焦点请优先移到第二p而不是“显示全部分p”按钮。
另外如果可能的话没有分p的视频页面请隐藏该按钮。

**Comment by liyk123** [comment]
要和#57 综合考虑

**Comment by wjz2001** [comment]
> 要和#57 综合考虑

确实，已修改附加信息
