### ISSUE TITLE
播放完后希望自动退出视频，目前是播放完自动暂停了😂

### ISSUE THREAD

**Issue by hanjintao1996** [aaa1115910/bv#5]
## 问题描述
清晰简明地描述问题的所在
【例如：”我在 xxx 时感到不方便。“】

## 描述解决方案
清晰简明地描述你所想要发生的事情，即解决方案

## 描述替换方案
解决该问题的备选方案

## 附加信息
添加你认为有必要的信息

**Comment by yangchaobalck** [comment]
个人觉的没有必要

**Comment by aaa1115910** [comment]
我也觉得没必要做

**Comment by drw2005** [comment]
其实这个还是有用的，体验更好吧。不过优先级可以放在后面有时间做。
