### ISSUE TITLE
暂停视频后离开 App 界面，回到 App 继续播放视频会卡在同一个画面

### ISSUE THREAD

**Issue by J03H82** [aaa1115910/bv#51]
### Bug 描述

暂停视频后离开 App 界面，回到 App 继续播放视频会卡在同一个画面，需要快进或快退一下才会正常播放

### 复现问题的步骤

```plain text
1. 暂停视频
2. 离开 App（回到电视主页 or 切换到其他 App）  
3. 返回 BV 继续播放
```

### 预期行为

正常播放

### 应用版本

0

### Android 版本

Amdroid 9

**Comment by liyk123** [comment]
这个问题需要重写Activity的生命周期事件，具体可以参考ExoPlayer的demo

**Comment by aaa1115910** [comment]
你这个卡住，是指按确认键没法继续播放吗？

**Comment by J03H82** [comment]
> 你这个卡住，是指按确认键没法继续播放吗？

点继续播放后，画面会一直卡在暂停时的画面，但声音和弹幕是正常继续的。

**Comment by wakaka123wakaka** [comment]
我也遇到了这种情况
