### ISSUE TITLE
【建议】希望能支持安卓4.4.2

### ISSUE THREAD

**Issue by amlkiller** [aaa1115910/bv#55]
### 问题描述

很多电视用户的电视盒子都是办宽带时送的盒子，破解后装上当贝。大多数运营商的电视盒子都是魔改的安卓4.4.2。

### 描述解决方案

把安卓SDKapi降到19 KK ，做下兼容适配，谢谢。

**Comment by aaa1115910** [comment]
Duplicate of #37
