### ISSUE TITLE
多p视频上下移动光标时焦点位置混乱

### ISSUE THREAD

**Issue by wjz2001** [aaa1115910/bv#57]
### 问题描述

第一种情况：
当光标从视频页推荐视频区域上移时移至对应位置的分p，如第一个视频移到p1，第二个视频移到p2，后面所有的视频移到p3。

第二种情况：
当光标从视频页简介区域下移时移至p2，此时该多p视频集数较少，如https://www.bilibili.com/video/BV1uv4y1v7Wg。

第三种情况：
当光标从视频页简介区域下移时移至p3，此时该多p视频集数较多，如https://www.bilibili.com/video/BV1sg411x7vS。

### 描述解决方案

当光标上下移动时，如果移到分p区域则焦点固定在p2。

**Comment by liyk123** [comment]
这个是个整体性的问题，如果固定位置的话，可以在考虑在视频简介下面加入继续播放按钮

**Comment by wjz2001** [comment]
> 这个是个整体性的问题，如果固定位置的话，可以在考虑在视频简介下面加入继续播放按钮

继续播放按钮不如放在收藏按钮旁边

**Comment by liyk123** [comment]
> > 这个是个整体性的问题，如果固定位置的话，可以在考虑在视频简介下面加入继续播放按钮
> 
> 继续播放按钮不如放在收藏按钮旁边

我的意思是需要这个按钮，放在那里要看设计

**Comment by aaa1115910** [comment]
在 e85100390f60176f17dbd4fbbaab0210b3a896da 里处理了一下这些横向列表的焦点
- 焦点移动到分 p 列表时会默认移动到 p1
- 会自动记住焦点在横向列表的位置，避免上下移动焦点的时候倒是列表乱滚动
