### ISSUE TITLE
启动显示大陆地区不支持

### ISSUE THREAD

**Issue by hanxiaofeng** [aaa1115910/bv#58]
### Bug 描述

安装后，启动app，显示下图：

### 复现问题的步骤

```plain text
1.安装

2.启动app
```

### 预期行为

是什么原因啊

### 截图

![image](https://user-images.githubusercontent.com/10582931/213074872-12c94d2b-f087-45b9-856a-4f4a1d2bcffb.png)

### 应用版本

0.1.4

### Android 版本

android 7.1.2

### 设备厂商及型号

pad

### 遇到问题的视频 avid 或 bvid

无

**Comment by aaa1115910** [comment]
这能减少很多麻烦事，何乐而不为呢
