### ISSUE TITLE
搜索界面呼出系统输入法后点击系统输入法的确认无反应

### ISSUE THREAD

**Issue by qinlili23333** [aaa1115910/bv#64]
### Bug 描述

系统：Fireos 6
在搜索框按确认打开系统输入法之后，系统输入法的确认键不生效，必须按返回

### 复现问题的步骤

```plain text
在搜索框按确认键打开系统输入法，然后按系统输入法的确认，无反应
```

### 预期行为

和netflix等一样，按输入法确认开始搜索

### 应用版本

0.1.6.r244

### Android 版本

7.1.2

### 设备厂商及型号

fire stick 4k (mantis)

**Comment by aaa1115910** [comment]
3b1251ccd2c77cee7207fae8b4a84e55d3686626
