### ISSUE TITLE
按返回键返回顶部后会闪退

### ISSUE THREAD

**Issue by J03H82** [aaa1115910/bv#65]
### Bug 描述

一、在关注列表按返回键返回顶部后，App 会闪退
二、按一次返回键退出播放有时无效，需要按两次才会退出播放

### 复现问题的步骤

```plain text
一、
1. 在关注列表往下翻几列
2. 按返回键

二、
1. 随意播放一个视频
2. 按返回键退出
```

### 预期行为

功能正常

### 应用版本

r244

### Android 版本

Android 9

**Comment by aaa1115910** [comment]
闪退问题 b2c2cb28fd696e7fd33f5a69e32e9f8812dc8833
