### ISSUE TITLE
搜索界面优化

### ISSUE THREAD

**Issue by wjz2001** [aaa1115910/bv#69]
### 问题描述

……

### 描述解决方案

1.点击搜索按钮进入搜索界面，此时光标默认放在搜索框上，按下center键直接开始输入并弹出输入法。
2.取消必须按返回才能移动光标的设定。

**Comment by aaa1115910** [comment]
第二点，麻烦提供一下相关演示视频，因为我并没有设置这类设定

**Comment by aaa1115910** [comment]
第一点，我没有设置默认焦点，是因为在请求焦点的时候会自动激活系统输入法（暂时还没好的解决方案

**Comment by wjz2001** [comment]
> 第二点，麻烦提供一下相关演示视频，因为我并没有设置这类设定

这个无法提供，因为页面上没有任何明显的提示，所以无法显示我做了什么操作。

我简单描述一下：当焦点在输入框上时，光标可以自由移动；当点击center键输入内容后，此时光标无法移动，只能按左右键在文字间移动，此时按下返回才能上下左右自由移动。

**Comment by wjz2001** [comment]
> 第一点，我没有设置默认焦点，是因为在请求焦点的时候会自动激活系统输入法（暂时还没好的解决方案
我记得焦点在输入框上时只会显示高亮边框，此时只有按下center才会激活输入法。

**Comment by aaa1115910** [comment]
> 



> > 第一点，我没有设置默认焦点，是因为在请求焦点的时候会自动激活系统输入法（暂时还没好的解决方案
> 
> 我记得焦点在输入框上时只会显示高亮边框，此时只有按下center才会激活输入法。 另外bbll和1.66的搜索实现都和我上面说的相同，其实我只是想完全复刻1.66的搜索页面。

Compose 的 OutlinedTextFiled 在请求焦点的时候在 android tv 上就会自动弹出输入法，但在手机上就不会弹出输入法，就挺奇怪的

**Comment by wjz2001** [comment]
> > 
> 
> > > 第一点，我没有设置默认焦点，是因为在请求焦点的时候会自动激活系统输入法（暂时还没好的解决方案
> > 
> > 
> > 我记得焦点在输入框上时只会显示高亮边框，此时只有按下center才会激活输入法。 另外bbll和1.66的搜索实现都和我上面说的相同，其实我只是想完全复刻1.66的搜索页面。
> 
> Compose 的 OutlinedTextFiled 在请求焦点的时候在 android tv 上就会自动弹出输入法，但在手机上就不会弹出输入法，就挺奇怪的

但是现在国内的盒子电视什么的基本都不是标准tv系统吧？就是个手机改版。我觉得弄了没啥问题。

**Comment by aaa1115910** [comment]
> > 第二点，麻烦提供一下相关演示视频，因为我并没有设置这类设定
> 
> 这个无法提供，因为页面上没有任何明显的提示，所以无法显示我做了什么操作。
> 
> 我简单描述一下：当焦点在输入框上时，光标可以自由移动；当点击center键输入内容后，此时光标无法移动，只能按左右键在文字间移动，此时按下返回才能上下左右自由移动。

第二点我复现了（模拟器上正常，真机就没法按下键移动焦点）

**Comment by aaa1115910** [comment]
加了下键移动焦点 c6a6c000dd969c43995c43c6ed5457ec8fbb8d7a
我又试了下，给 textfiled 请求焦点会自动弹出系统键盘（chromecast）
