### ISSUE TITLE
主页增加推荐栏目及能看UP主所有视频安排一下下

### ISSUE THREAD

**Issue by yangchaobalck** [aaa1115910/bv#7]
## 问题描述
1.主页增加推荐栏目
 动态看完了，就想刷刷推荐，望开发者安排下。
2.能看UP主所有视频
看到一个UP主的视频挺有意思，就想看看该UP主的所有视频，有时间也安排下

开发者辛苦了！！！

**Comment by aaa1115910** [comment]
建议分为两个 issue 提出，所以我会将该 issue 关闭

up主视频会更先做，主页推荐暂时不会做
