### ISSUE TITLE
第三方遥控器无法使用OK键播放/暂停，只有电视原始遥控器的中间ok键可以。

### ISSUE THREAD

**Issue by NilesCaulder** [aaa1115910/bv#70]
### Bug 描述

第三方飞鼠的中间键OK，在播放时无妨开始播放/暂停，只有电视原版遥控器的ok键可以。所以盒子只有飞鼠的话，使用BV无法随意暂停了。

猜测可能是key binding的问题，第三方遥控器的中键实际上是键盘ENTER键，大部分情况下和正经确认键一致。

希望作者能将开始/暂停的触发的按键范围扩大一些。

### 复现问题的步骤

```plain text
开始播放，按遥控器中间键
```

### 预期行为

暂停

### 应用版本

BV-255-0.1.7.r255.4653e34

### Android 版本

Android 11

### 设备厂商及型号

nVIDIA Shield TV

**Comment by aaa1115910** [comment]
添加了多个按键的事件监听 c7c2e2dbb16406cc957f3c497d88ba09429d7c7b
但我没有测试（懒
你可以在 https://github.com/aaa1115910/bv/actions/workflows/alpha.yml 获取到最新版本试试
