### ISSUE TITLE
播放 4K 视频出现画面上下位移

### ISSUE THREAD

**Issue by Connor1996** [aaa1115910/bv#72]
### Bug 描述

播放某些 4K 视频时，无论 H264/H265 都会出现画面上下位移的情况

### 复现问题的步骤

```plain text
打开视频直接播放
```

### 预期行为

画面正常

### 截图

![IMG_3605](https://user-images.githubusercontent.com/13497871/219705297-58b29592-77eb-4ac5-b17c-efd1dd1101b7.jpg)

### 应用版本

0.1.6.r238.2727e72.release

### Android 版本

Android 10

### 设备厂商及型号

XIAOMI - MiTV 6 OLED 

### 附加信息

- 影视飓风的多数新视频都有这个问题
  - 有问题的 4K 视频如 https://www.bilibili.com/video/BV1ZM411E7FY 
  - 没问题的 4K 视频如 https://www.bilibili.com/video/BV1Ad4y1j7Ae
- 其他 UP 的 4K 视频几乎没有这个问题，只有极个别碰到过
- 出现问题时候，画面最下面和最上面会有颜色条（绿色或彩色），不确定是不是解码器问题

**Comment by aaa1115910** [comment]
看到隔壁 bbll 也有这问题，解码器都是用的硬解（除 av1），所以视频播放效果和设备本身有关，这问题我也找不到原因（摊手.jpg）

**Comment by Connor1996** [comment]
好的，感谢回复
