### ISSUE TITLE
搜索界面输入法无法正常使用

### ISSUE THREAD

**Issue by wjz2001** [aaa1115910/bv#73]
### Bug 描述

弹出输入法后按下键输入法就会消失，因此无法打字。
0.17及之前版本没问题。

### 复现问题的步骤

```plain text
1.进入搜索界面；
2.光标移至输入框，按center键打开输入法；
3.按下键，输入法消失。
```

### 预期行为

在输入法上可以自由移动光标，输入法不会消失。

### 应用版本

0.1.8.r272.242a194.release

### Android 版本

Android 9

### 设备厂商及型号

hk1 box

**Comment by aaa1115910** [comment]
嘶，仔细一想，我的锅，用 bug 修复 bug 。。。。。

**Comment by aaa1115910** [comment]
但 Google TV 自带的 gboard 使用正常。。。。

**Comment by wjz2001** [comment]
> 但 Google TV 自带的 gboard 使用正常。。。。

我的是搜狗输入法电视版，当贝下载的

**Comment by leeo999** [comment]
没空修改一下？

**Comment by JulianLU9** [comment]
我的也是同样问题

**Comment by leeo999** [comment]
换个输入法即可。

发自我的iPad

**Comment by JulianLU9** [comment]
> 换个输入法即可。 发自我的iPad
> […](#)
> 在 2023年5月18日，20:14，JulianLU9 ***@***.***> 写道： ﻿ 我的也是同样问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

不好意思，我的电视上只有一种输入法。

**Comment by leeo999** [comment]
你装个不就行了，装百度，搜狗有问题。发自移动平台在 2023年5月18日，21:40，JulianLU9 ***@***.***> 写道：﻿

换个输入法即可。 发自我的iPad
…
在 2023年5月18日，20:14，JulianLU9 @.***> 写道： ﻿ 我的也是同样问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

不好意思，我的电视上只有一种输入法。
