### ISSUE TITLE
新版BV频繁卡死闪退

### ISSUE THREAD

**Issue by werg18** [aaa1115910/bv#81]
### Bug 描述

在使用新版本BV后，会频繁遇到卡死，白屏，闪退等问题(在配置较低的电视上使用)

### 复现问题的步骤

```plain text
第一种卡死:点击加载视频中卡死在黑屏缓冲中，但声音却正常播放，第二种卡死：首先点击进入视频中卡死在loading界面中，第三种卡死：正常播放视频，画面突然卡死，声音正常，在使用过程中有时会白屏闪退，有时在界面中突然卡死返回主页
```

### 预期行为

希望能解决这些问题

### 应用版本

0.0.1

### Android 版本

安卓5.1

### 设备厂商及型号

Hisense

**Comment by aaa1115910** [comment]
卡缓冲多半是和隔壁bbll一样的source error，这和设备本身有关
卡Loading你得提供一个可以复现的步骤
第三个情况。。。。我没遇到过，可能和bv吃性能有关

**Comment by werg18** [comment]
之前版本没遇到卡死和闪退，最近新版本太频繁了，所以有些影响，当然可能是我配置较低的影响，所以会频繁遇到

aaa1115910 ***@***.***> 于 2023年4月19日周三 10:52写道：

**Comment by werg18** [comment]
因为之前版本没遇到卡死和闪退，但最近新版本太频繁了，有些影响，当然可能是我配置较低的影响，所以会频繁遇到

**Comment by werg18** [comment]
> 

因为之前版本没遇到卡死和闪退，但最近新版本太频繁了，有些影响，当然可能是我配置较低的影响，所以会频繁遇到

**Comment by werg18** [comment]
> 卡缓冲多半是和隔壁bbll一样的source error，这和设备本身有关 卡Loading你得提供一个可以复现的步骤 第三个情况。。。。我没遇到过，可能和bv吃性能有关

因为之前版本没遇到卡死和闪退，但最近新版本太频繁了，有些影响，当然可能是我配置较低的影响，所以会频繁遇到

**Comment by liyk123** [comment]
有没有一种可能是你的设备环境发生变化造成的问题，建议检查一下设备可用的存储空间还有运行时内存剩余空间

**Comment by werg18** [comment]
好的👌

**Comment by werg18** [comment]
> 有没有一种可能是你的设备环境发生变化造成的问题，建议检查一下设备可用的存储空间还有运行时内存剩余空间

是的，所以是低配设备会多次出现这些问题，在我使用高配盒子设备等基本没遇到过，使用低配设备会大概率遇到
