### ISSUE TITLE
CC字幕无法使用

### ISSUE THREAD

**Issue by werg18** [aaa1115910/bv#82]
### Bug 描述

按菜单打开管理CC字幕无法使用那一栏只有关闭按钮没有打开按钮

### 复现问题的步骤

```plain text
按菜单打开管理CC字幕无法使用那一栏只有关闭按钮没有打开按钮
```

### 预期行为

希望作者解决

### 应用版本

0.0.1

### Android 版本

5.1

### 设备厂商及型号

Hisense

### 附加信息

CC字幕那一栏只有关闭按钮并没有打开按钮

**Comment by aaa1115910** [comment]
48fbedafdbf214ffccff188f0ce9695fbc0f6d90
