### ISSUE TITLE
番剧进入详细页不能直接点击封面播放

### ISSUE THREAD

**Issue by werg18** [aaa1115910/bv#83]
### 问题描述

番剧综艺不能像视频一样进入详细页，点击封面就可以直接播放必须要移动到继续播放才能播放

### 描述解决方案

像视频一样，点击进入详细页点击封面就可以直接播放

**Comment by aaa1115910** [comment]
原本我是想把封面点击留给其他功能的，但考虑到一些使用习惯学习成本就没做。。。。

**Comment by werg18** [comment]
> 原本我是想把封面点击留给其他功能的，但考虑到一些使用习惯学习成本就没做。。。。

只是建议，参考就行
