### ISSUE TITLE
番剧视频历史记录出现问题

### ISSUE THREAD

**Issue by werg18** [aaa1115910/bv#84]
### Bug 描述

在观看番剧途中用遥控器上键调出快捷选集，选了下一集，观看之后，退回详细页，却没有记录，而是你之前点进播放番剧的历史记录，快进番剧，退回详细页，也没有记录，只是重新开始播放，视频也同理

### 复现问题的步骤

```plain text
在观看番剧途中用遥控器上键调出快捷选集，选了下一集，观看之后，退回详细页，却没有记录，而是你之前点进播放番剧的历史记录，快进番剧，退回详细页，也没有记录，只是重新开始播放，视频也同理
```

### 预期行为

希望作者修复历史记录

### 应用版本

0.0.1

### Android 版本

5.1

### 设备厂商及型号

Hisense

**Comment by aaa1115910** [comment]
视频播放记录和 48fbedafdbf214ffccff188f0ce9695fbc0f6d90 有关
