### ISSUE TITLE
获取番剧时间表有大概率会获取失败

### ISSUE THREAD

**Issue by werg18** [aaa1115910/bv#86]
### Bug 描述

番剧分区点击时间表会有大概率获取失败(遥控器操控光标移到番剧轮播图往下移会卡顿一下光标往上移不是到番剧分区而是光标自动转移到动态)索引点击白屏，不知是bug还是没写

### 复现问题的步骤

```plain text
点击番剧分区遥控器光标移到番剧轮播图卡顿一下，移到时间表点击很大概率获取失败，遥控器光移回番剧轮播图上移自动跳转到动态分区
```

### 预期行为

修复时间表大概率获取失败问题，修复番剧轮播图遥控器光标下移卡顿问题，番剧轮播图光标上移自动跳转动态分区问题

### 应用版本

0.1.10

### Android 版本

5.1

### 设备厂商及型号

Hisense

### 附加信息

卡死问题还是希望能优化一下

**Comment by werg18** [comment]
刚刚确认了一下，番剧时间表本身没问题只是会显示提示获取失败

**Comment by aaa1115910** [comment]
**建议不同的问题各开一个 issue，而不是全写在一块**

**Comment by werg18** [comment]
因为这些问题相关度高都是小问题，所以我全写了，下次会的

**Comment by werg18** [comment]
> **建议不同的问题各开一个 issue，而不是全写在一块**

因为这些问题相关度高都是小问题，所以我全写了，下次会的

**Comment by aaa1115910** [comment]
我还没有遇到过时间表加载失败的情况，没办法复现
轮播图往下移动卡顿是 Google 写的 bug
上移焦点错误还没时间去折腾，要改比较麻烦
索引完全没写（理直气壮！）
