### ISSUE TITLE
希望增加显示底部常驻进度条功能

### ISSUE THREAD

**Issue by werg18** [aaa1115910/bv#88]
### 问题描述

在应用设置中增加一个显示底部常住进度条功能，可以在观看视频时，实时看到进度条

### 描述解决方案

![IMG_20230429_234358](https://user-images.githubusercontent.com/124438602/235311385-48eaf107-d298-4bd5-a7ed-8f5e120eba8c.jpg)
![IMG_20230429_234557](https://user-images.githubusercontent.com/124438602/235311387-325eb07d-d96f-435b-959a-0180ca5d12ea.jpg)

**Comment by aaa1115910** [comment]
我觉得会影响观感，没有计划添加

**Comment by werg18** [comment]
> 我觉得会影响观感，没有计划添加

好的
