### ISSUE TITLE
出现无法在中国大陆区域使用问题

### ISSUE THREAD

**Issue by vvvvffff** [aaa1115910/bv#90]
### Bug 描述

出现无法在中国大陆区域使用大粉屏

### 复现问题的步骤

```plain text
出现无法在中国大陆区域使用大粉屏
```

### 预期行为

出现无法在中国大陆区域使用大粉屏

### 截图

出现无法在中国大陆区域使用大粉屏

### 应用版本

BV-326-0.1.11.r326

### Android 版本

Android 9

### 设备厂商及型号

腾讯盒子

**Comment by aaa1115910** [comment]
Duplicate of #77
