### ISSUE TITLE
0.1.11版本无法退出应用

### ISSUE THREAD

**Issue by konglang616** [aaa1115910/bv#91]
### Bug 描述

Version 0.1.11.r326.e602b69.release (326)
设备 斐讯T1
进入APP后无法像上一版本0.1.10按两次遥控器返回键退出APP

### 复现问题的步骤

```plain text
1.进入BV
2.双击返回键无法退出APP
```

### 预期行为

修复双击返回键退出APP功能

### 应用版本

0.1.11.r326.e602b69.release (326)

### Android 版本

Android 7.1.2

### 设备厂商及型号

PHICOMM T1

**Comment by aaa1115910** [comment]
Duplicate of #87

**Comment by werg18** [comment]
好像在番剧分区可以正常退出
