### ISSUE TITLE
点击up主名字不显示视频列表

### ISSUE THREAD

**Issue by werg18** [aaa1115910/bv#92]
### Bug 描述

点击up主名字进入空间不显示视频列表 都是0视频，需要多点几次才有概率成功

### 复现问题的步骤

```plain text
点击up主名字进入up主空间，显示已加载0条数据，
```

### 预期行为

点击一次能直接显示视频

### 截图

![Uploading IMG_20230506_042718.jpg…]()

### 应用版本

0.1.11

### Android 版本

5.1

**Comment by aaa1115910** [comment]
8f78c368f96e1fdfc2ce8819235c364f5b1669d1

**Comment by aaa1115910** [comment]
要获取最新版本可以去 [Actions](https://github.com/aaa1115910/bv/actions/workflows/alpha.yml) 里下载自动构建的 alpha 版
