### ISSUE TITLE
进入视频详情页显示illegal input

### ISSUE THREAD

**Issue by Snow-Maple94** [aaa1115910/bv#93]
### Bug 描述

今天23-05-08进入视频详情时页黑屏显示illegal input，昨天晚上使用还是正常的

### 复现问题的步骤

```plain text
NA
```

### 预期行为

希望能修复吧，谢谢！

### 截图

![IMG_20230508_225122](https://user-images.githubusercontent.com/125074453/236857684-6239ea6b-b5fd-43e5-9961-ef7465be8535.jpg)

### 应用版本

0.1.11

### Android 版本

Android 10

### 设备厂商及型号

Sony x85k

**Comment by aaa1115910** [comment]
**遇到问题的视频 avid 或 bvid**
**遇到问题的视频 avid 或 bvid**
**遇到问题的视频 avid 或 bvid**

**Comment by werg18** [comment]
> **遇到问题的视频 avid 或 bvid** **遇到问题的视频 avid 或 bvid** **遇到问题的视频 avid 或 bvid**

BV1ya4y1g7nY BV19k4y1j7h8 目前我遇到两个视频会这样
