### ISSUE TITLE
部分视频播放出现Illegal Input报错提示

### ISSUE THREAD

**Issue by romiwangqian** [aaa1115910/bv#94]
### Bug 描述

部分视频播放出现Illegal Input报错提示
复现：这个up主https://space.bilibili.com/3334179?spm_id_from=333.337.0.0 的视频都报错Illegal Input

### 复现问题的步骤

```plain text
复现：这个up主https://space.bilibili.com/3334179?spm_id_from=333.337.0.0 的视频都报错Illegal Input
```

### 预期行为

正常播放

### 应用版本

最新版

### Android 版本

Android 10

### 设备厂商及型号

Sony XR-75X90J

### 遇到问题的视频 avid 或 bvid

https://www.bilibili.com/video/BV1Pk4y1L7Ni/?spm_id_from=333.999.0.0

**Comment by aaa1115910** [comment]
Duplicate of #93
