### ISSUE TITLE
按遥控菜单键有概率呼不出菜单控制

### ISSUE THREAD

**Issue by werg18** [aaa1115910/bv#95]
### Bug 描述

遥控器按菜单键 第一次成功呼出菜单控制 后就无法呼出，按暂停时可成功呼出一次或多次 再取消后也可成功呼出几次

### 复现问题的步骤

```plain text
遥控器按菜单键第一次成功呼出菜单控制后无法呼出，按暂停时可成功呼出一次或多次 再取消后也可成功呼出几次
```

### 预期行为

按菜单键每次都可成功呼出菜单控制

### 应用版本

0.2.0.r414.79b897e.release

### Android 版本

5.1

**Comment by aaa1115910** [comment]
我一直都是用的长按 center 键，因为我没菜单键。。。。。

werg18 ***@***.***> 于 2023年5月14日周日 06:30写道：
